import { ConnectButton } from '@rainbow-me/rainbowkit';
import { MultisigWallet } from '@skaleproject/multisig-wallet';
import { Wallet } from 'ethers';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useSigner } from 'wagmi';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  const { data: signer } = useSigner();  
  const [owners, setOwners] = useState<string[]>([]);
  const [msg, setMsg] = useState<MultisigWallet>(new MultisigWallet({
    rpcUrl: "https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar",
    signer: signer as Wallet
  }));

  const addresses = async() => {
    const res = await msg.getOwners();
    setOwners(res);
  }

  useEffect(() => {
    const update = async() => {
      await addresses();
    }

    update();
  }, []) 


  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Owners</h2>
        {owners && owners.map((owner: string, index: number) => {
          return (
            <div key={index}>
              <p>{owner}</p>
              <button onClick={async(e) => {
                e.preventDefault();
                await msg.removeOwner({
                  address: owner
                });
              }}>Remove Owner</button>
            </div>
          );
        })}
      </main>
    </div>
  );
};

export default Home;
